<a href="https://colab.research.google.com/github/Mcflurrins/ByteFest-hackathon/blob/main/EDA_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import pandas as pd

df_31 = pd.read_csv("data/table_31.csv", on_bad_lines='skip')
df_32 = pd.read_csv("data/table_32.csv", on_bad_lines='skip')
df_28 = pd.read_csv("data/table_28.csv", on_bad_lines='skip')

In [3]:
df_31.head()

,Category,Postgraduate Degree,Graduate Diploma / Graduate Certificate,Bachelor Degree,Advanced Diploma/Diploma,Certificate III/IV,Certificate I/II,Certificate n.f.d.,Total with non-school qualification(a),Without non-school qualification,Total(a)
0,Male,741.2,191.9,1566.2,694.3,1561.2,117.0,76.5,5066.1,2278.8,7344.8
1,Female,779.0,328.3,1881.2,748.5,871.7,108.9,51.2,4878.3,1919.6,6798.4
2,15–19,0.0,0.0,2.2,9.9,46.5,30.9,4.5,105.0,713.0,815.9
3,20–24,19.1,15.1,269.5,84.4,200.6,33.2,16.2,651.2,713.8,1362.0
4,25–34,433.7,100.9,1145.2,289.4,600.8,40.1,31.3,2687.5,664.1,3351.7

In [4]:
df_32.head()

,Category,Skill level 1 (highest),Skill level 2,Skill level 3,Skill level 4,Skill level 5 (lowest),Total ('000)
0,Males,2446.6,837.0,1428.3,1589.4,1001.7,7344.8
1,Females,2515.1,770.6,433.4,2056.6,993.6,6798.4
2,15–24,272.7,147.0,365.7,647.9,732.9,2178.3
3,25–34,1265.9,396.7,472.5,817.3,378.7,3351.7
4,35–44,1391.6,394.6,408.2,746.3,261.3,3214.0

In [12]:
df_combined = pd.merge(df_31, df_32, on='Category', how='inner')
df_combined

,Category,Postgraduate Degree,Graduate Diploma / Graduate Certificate,Bachelor Degree,Advanced Diploma/Diploma,Certificate III/IV,Certificate I/II,Certificate n.f.d.,Total with non-school qualification(a),Without non-school qualification,Total(a),Skill level 1 (highest),Skill level 2,Skill level 3,Skill level 4,Skill level 5 (lowest),Total ('000)
0,25–34,433.7,100.9,1145.2,289.4,600.8,40.1,31.3,2687.5,664.1,3351.7,1265.9,396.7,472.5,817.3,378.7,3351.7
1,35–44,509.1,136.2,938.2,361.3,537.6,26.8,41.0,2601.9,613.1,3214.0,1391.6,394.6,408.2,746.3,261.3,3214.0
2,45–54,314.7,140.6,659.2,358.6,503.2,36.0,18.3,2082.3,641.7,2721.5,1085.4,359.0,306.6,687.1,270.2,2721.5
3,55–64,179.9,101.6,337.3,267.7,421.3,37.7,9.1,1401.1,640.4,2043.4,697.0,248.0,248.3,588.1,251.9,2043.4
4,65–74,63.7,29.6,96.1,71.9,120.9,19.1,6.1,418.4,212.9,632.2,247.5,62.3,59.8,163.1,97.7,632.2
5,Agriculture forestry and fishing,9.0,5.4,33.9,25.3,60.2,14.8,4.6,156.7,145.7,301.0,161.9,14.0,13.0,45.5,65.0,301.0
6,Mining,15.5,4.9,48.1,20.0,85.9,2.3,3.5,186.4,72.7,257.1,71.7,28.4,47.6,101.5,11.4,257.1
7,Manufacturing,53.4,15.6,154.5,90.3,208.8,14.1,8.3,563.8,334.3,897.6,221.1,63.6,221.5,230.6,150.9,897.6
8,Construction,41.0,12.8,139.6,112.0,524.5,28.0,24.3,901.5,447.0,1349.1,213.2,106.9,635.5,247.4,142.7,1349.1
9,Wholesale trade,37.1,8.2,69.6,40.9,59.8,10.3,2.2,229.8,147.5,375.2,133.9,26.8,30.6,140.4,41.5,375.2
10,Retail trade,68.1,16.0,184.4,92.3,157.9,25.7,11.4,569.8,699.4,1269.2,132.8,181.3,69.7,224.0,649.9,1269.2
11,Accommodation and food services,35.3,9.8,129.2,88.7,106.8,20.5,9.6,406.2,524.2,931.0,19.1,247.1,40.7,267.5,350.8,931.0
12,Transport postal and warehousing,40.6,9.9,125.1,79.4,122.5,16.7,8.4,413.0,303.9,716.4,106.0,33.6,26.7,449.4,96.4,716.4
13,Information media and telecommunications,26.5,5.8,80.2,25.8,23.7,2.1,0.0,169.7,38.2,205.1,102.0,27.6,31.9,34.1,10.3,205.1
14,Financial and insurance services,85.5,30.2,188.1,71.1,31.9,1.5,1.0,420.2,94.1,514.3,252.6,71.1,33.7,155.9,3.8,514.3
15,Rental hiring and real estate services,19.1,7.6,58.1,30.3,36.3,4.2,8.4,170.9,56.0,226.9,47.5,44.2,91.7,31.3,14.0,226.9
16,Professional scientific and technical services,258.7,63.2,572.2,117.3,91.8,9.4,4.1,1136.1,170.9,1309.0,978.5,142.3,59.9,103.6,20.4,1309.0
17,Administrative and support services,26.5,8.4,91.4,53.0,69.6,5.9,4.5,269.8,161.1,431.9,89.7,44.5,54.4,85.2,155.5,431.9
18,Public administration and safety,140.3,61.7,261.2,125.4,122.2,12.7,2.4,739.6,174.9,916.7,391.9,166.6,53.7,219.1,81.0,916.7
19,Education and training,264.8,112.3,415.5,100.7,105.8,10.4,7.4,1034.4,164.6,1196.9,772.8,53.8,53.6,269.1,35.1,1196.9
20,Health care and social assistance,340.6,124.1,711.7,249.4,351.8,29.6,17.5,1862.4,401.6,2260.9,1033.9,261.3,52.5,822.5,87.8,2260.9
21,Arts and recreation services,19.0,9.1,60.8,30.2,46.7,3.3,3.4,179.7,87.7,265.4,85.5,28.9,54.1,59.4,35.1,265.4
22,Other services,22.0,8.9,68.1,72.0,182.7,9.8,7.6,380.7,129.1,509.8,58.1,44.4,256.3,121.5,28.9,509.8
23,Total,1520.1,521.1,3448.0,1442.9,2433.4,224.4,127.2,9948.0,4198.9,14144.8,4963.3,1610.2,1858.0,3647.0,1994.3,14144.8

In [13]:
df_combined['Diff with/without qualification'] = df_combined['Total with non-school qualification(a)'] - df_combined['Without non-school qualification']
df_combined

,Category,Postgraduate Degree,Graduate Diploma / Graduate Certificate,Bachelor Degree,Advanced Diploma/Diploma,Certificate III/IV,Certificate I/II,Certificate n.f.d.,Total with non-school qualification(a),Without non-school qualification,Total(a),Skill level 1 (highest),Skill level 2,Skill level 3,Skill level 4,Skill level 5 (lowest),Total ('000),Diff with/without qualification
0,25–34,433.7,100.9,1145.2,289.4,600.8,40.1,31.3,2687.5,664.1,3351.7,1265.9,396.7,472.5,817.3,378.7,3351.7,2023.4
1,35–44,509.1,136.2,938.2,361.3,537.6,26.8,41.0,2601.9,613.1,3214.0,1391.6,394.6,408.2,746.3,261.3,3214.0,1988.8
2,45–54,314.7,140.6,659.2,358.6,503.2,36.0,18.3,2082.3,641.7,2721.5,1085.4,359.0,306.6,687.1,270.2,2721.5,1440.6
3,55–64,179.9,101.6,337.3,267.7,421.3,37.7,9.1,1401.1,640.4,2043.4,697.0,248.0,248.3,588.1,251.9,2043.4,760.7
4,65–74,63.7,29.6,96.1,71.9,120.9,19.1,6.1,418.4,212.9,632.2,247.5,62.3,59.8,163.1,97.7,632.2,205.5
5,Agriculture forestry and fishing,9.0,5.4,33.9,25.3,60.2,14.8,4.6,156.7,145.7,301.0,161.9,14.0,13.0,45.5,65.0,301.0,11.0
6,Mining,15.5,4.9,48.1,20.0,85.9,2.3,3.5,186.4,72.7,257.1,71.7,28.4,47.6,101.5,11.4,257.1,113.7
7,Manufacturing,53.4,15.6,154.5,90.3,208.8,14.1,8.3,563.8,334.3,897.6,221.1,63.6,221.5,230.6,150.9,897.6,229.5
8,Construction,41.0,12.8,139.6,112.0,524.5,28.0,24.3,901.5,447.0,1349.1,213.2,106.9,635.5,247.4,142.7,1349.1,454.5
9,Wholesale trade,37.1,8.2,69.6,40.9,59.8,10.3,2.2,229.8,147.5,375.2,133.9,26.8,30.6,140.4,41.5,375.2,82.3
10,Retail trade,68.1,16.0,184.4,92.3,157.9,25.7,11.4,569.8,699.4,1269.2,132.8,181.3,69.7,224.0,649.9,1269.2,-129.6
11,Accommodation and food services,35.3,9.8,129.2,88.7,106.8,20.5,9.6,406.2,524.2,931.0,19.1,247.1,40.7,267.5,350.8,931.0,-118.0
12,Transport postal and warehousing,40.6,9.9,125.1,79.4,122.5,16.7,8.4,413.0,303.9,716.4,106.0,33.6,26.7,449.4,96.4,716.4,109.1
13,Information media and telecommunications,26.5,5.8,80.2,25.8,23.7,2.1,0.0,169.7,38.2,205.1,102.0,27.6,31.9,34.1,10.3,205.1,131.5
14,Financial and insurance services,85.5,30.2,188.1,71.1,31.9,1.5,1.0,420.2,94.1,514.3,252.6,71.1,33.7,155.9,3.8,514.3,326.1
15,Rental hiring and real estate services,19.1,7.6,58.1,30.3,36.3,4.2,8.4,170.9,56.0,226.9,47.5,44.2,91.7,31.3,14.0,226.9,114.9
16,Professional scientific and technical services,258.7,63.2,572.2,117.3,91.8,9.4,4.1,1136.1,170.9,1309.0,978.5,142.3,59.9,103.6,20.4,1309.0,965.2
17,Administrative and support services,26.5,8.4,91.4,53.0,69.6,5.9,4.5,269.8,161.1,431.9,89.7,44.5,54.4,85.2,155.5,431.9,108.7
18,Public administration and safety,140.3,61.7,261.2,125.4,122.2,12.7,2.4,739.6,174.9,916.7,391.9,166.6,53.7,219.1,81.0,916.7,564.7
19,Education and training,264.8,112.3,415.5,100.7,105.8,10.4,7.4,1034.4,164.6,1196.9,772.8,53.8,53.6,269.1,35.1,1196.9,869.8
20,Health care and social assistance,340.6,124.1,711.7,249.4,351.8,29.6,17.5,1862.4,401.6,2260.9,1033.9,261.3,52.5,822.5,87.8,2260.9,1460.8
21,Arts and recreation services,19.0,9.1,60.8,30.2,46.7,3.3,3.4,179.7,87.7,265.4,85.5,28.9,54.1,59.4,35.1,265.4,92.0
22,Other services,22.0,8.9,68.1,72.0,182.7,9.8,7.6,380.7,129.1,509.8,58.1,44.4,256.3,121.5,28.9,509.8,251.6
23,Total,1520.1,521.1,3448.0,1442.9,2433.4,224.4,127.2,9948.0,4198.9,14144.8,4963.3,1610.2,1858.0,3647.0,1994.3,14144.8,5749.1